### ISSUE TITLE
Customizable color detection area?

### ISSUE THREAD

**Issue by JaeXun** [dewgenenny/ScreenSync#1]
This script works well, nice job. Is there a way I can adjust the color detection area? I use an ultrawide monitor and noticed it only captures a particular area, the top left corner and would like to maybe customize it. Thank you for all the good work.

**Comment by dewgenenny** [comment]
Hey, I'm working on this! The version I just released allows you to select bounding box sizes, however they're based on a 1080p monitor. Will work on a version that is based on percentages of the screen instead.

**Comment by dewgenenny** [comment]
Hey @JaeXun I just uploaded a new release that allows you to choose from small (5%) through to xlarge (50%) of the screen to be used as the bounding box / color detection area. You can use the GUI to select and it will be changed on the fly :)
