### ISSUE TITLE
Windows standalone installer not working on W10 64bits environment

### ISSUE THREAD

**Issue by MaeseT** [dewgenenny/ScreenSync#2]

**Comment by dewgenenny** [comment]
Hey I'm so sorry, I didn't notice this issue! I just released new versions - the new file I just released (https://github.com/dewgenenny/ScreenSync/releases/download/0.3/ScreenSync.exe) is built using pyinstaller as 'all-in-one' and should work correctly :)

**Comment by MaeseT** [comment]
Thank you, I will try it out as soon as I will be on the target environment
